---
functional:
- требование 3
- требование 4
- требование 8
- требование 11
- требование 12
non-functional:
- требование 1
- требование 2
- требование 5
- требование 6
- требование 7
- требование 9
implicit:
- удобство использования интерфейса 
- сохранение выбранных опций фильтров при дальнейшей работе с сайтом
- корректная работа фильтров при переходе на следующую страницу каталога
- сохранение содержимого корзины при переходе на следующую страницу каталога
- правильное отображение скидок на товары 
- проверка наличия товара перед оформлением в корзину
- сохранение языка интерфейса при обновлении страницы
- своевременное уведомление об ошибках при работе с сайтом на разных этапах
