---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность переключить язык интерфейса
- Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Сайт должен быть доступен на различных устройствах
implicit:
- удобство использования интерфейса 
- сохранение выбранных опций фильтров при дальнейшей работе с сайтом
- корректная работа фильтров при переходе на следующую страницу каталога
- сохранение содержимого корзины при переходе на следующую страницу каталога
- правильное отображение скидок на товары 
- проверка наличия товара перед оформлением в корзину
- сохранение языка интерфейса при обновлении страницы
- своевременное уведомление об ошибках при работе с сайтом на разных этапах
